# Generated by Django 2.0 on 2017-12-24 12:54

from django.db import migrations, models
import django.db.models.deletion
import domain.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chairman',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChairmanOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'chairman_orders',
                'abstract': False,
            },
            bases=(domain.models.AsDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facilitator',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilitatorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'facilitator_orders',
                'abstract': False,
            },
            bases=(domain.models.AsDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'members',
            },
            bases=(domain.models.AsDictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='facilitatororder',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Member'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Member'),
        ),
        migrations.AddField(
            model_name='chairmanorder',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Member'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Member'),
        ),
    ]
