# Generated by Django 2.0 on 2017-12-23 14:46

from django.db import migrations, models
import django.db.models.deletion
import domain.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Member')),
            ],
            options={
                'db_table': 'facilitator',
            },
        ),
        migrations.CreateModel(
            name='FacilitatorAssignedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.IntegerField(choices=[(1, 'assign'), (2, 'redo')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facilitator_assigned_logs',
            },
        ),
        migrations.CreateModel(
            name='FacilitatorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Member')),
            ],
            options={
                'db_table': 'facilitator_orders',
            },
            bases=(domain.models.AsDictMixin, models.Model),
        ),
    ]
