FROM python:alpine

RUN apk --no-cache --update add \
  gcc \
  musl-dev \
  postgresql-dev
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY . /app
RUN pip install -r requirements.txt
